# GHC 9.2.5
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-20.06

packages:
- .

extra-deps:
- diff-loc-0.1.0.0
- levenshtein-0.2.1.0

nix:
  packages: [zlib]
